version: "3"

services:
  app:
    image: iagosrm/nodejs-poc
    ports:
      - 3000:3000
    depends_on:
      - "dev-postgres"
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
  # test-redis:
  #   image: redis
  #   ports:
  #     - 6380:6379
  dev-redis:
    image: redis
    ports:
      - 6379:6379
  dev-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=dev:dev-redis:6379,test:test-redis:6379
  #     # - REDIS_HOSTS=dev:dev-redis:6379
  #     # - REDIS_HOSTS=test:test-redis:6379
  #   ports:
  #     - "8081:8081"
